### ISSUE TITLE
Configuration format

### ISSUE THREAD

**Issue by IanChen83** [Destinia/Vision#7]
## For human-editable configuration format
```yaml
# chart-id should be a unique, valid name
chart:
  # (required)
  title: "Title"

  # (optional)
  description: "Some description"

  # Multiple sources (optional)
  sources:
    - name: "source-name"
      type: "chart type"

    - name: "source-name"
      type: "chart type"

    - name: "source-name"
      type: "chart type"

  # Data is filtered to be in the range of [start, end]
  # Both start & end is in RFC3339 format

  # (optional, default to the first data)
  # If start is negative, it means the offset from end
  start: -3600

  # (optional, default to now)
  end: 2018-07-28T07:32:00Z

  # (optional, only useful when agg_func is set)
  segment: 60

  # (optional)
  agg_func: "average"
```
